apply plugin: 'com.android.library'

android {
    namespace 'com.mparticle.compat.javaconsumer'
    compileSdk 33
    defaultConfig {
        minSdk 21
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "com.mparticle:android-core:$mparticleSdkVersion"
    implementation "com.mparticle:android-kit-base:$mparticleSdkVersion"
}
