version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  target-branch: "development"
  labels: [ "dependabot" ]
  schedule:
    interval: "daily"
  open-pull-requests-limit: 10
  commit-message:
    prefix: "chore"
