name: Auto respond and close issue

on:
  issues:
    types:
      - opened

jobs:
  auto-respond-and-close-issue:
    uses: mparticle/mparticle-workflows/.github/workflows/auto-respond-close-issue.yml@main
    with:
      issue_number: ${{ github.event.issue.number }}
      repository: ${{ github.repository }}
      user_login: ${{ github.event.issue.user.login }}